version: "3.8"

services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: jobbooster-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    networks:
      - jobbooster-network

  # Langfuse (Observability)
  langfuse-db:
    image: postgres:16-alpine
    container_name: jobbooster-langfuse-db
    environment:
      POSTGRES_USER: langfuse
      POSTGRES_PASSWORD: langfuse
      POSTGRES_DB: langfuse
    volumes:
      - langfuse_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jobbooster-network

  langfuse:
    image: langfuse/langfuse:latest
    container_name: jobbooster-langfuse
    depends_on:
      - langfuse-db
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://langfuse:langfuse@langfuse-db:5432/langfuse
      NEXTAUTH_URL: http://localhost:3001
      NEXTAUTH_SECRET: changeme-generate-a-random-secret
      SALT: changeme-generate-a-random-salt
    restart: unless-stopped
    networks:
      - jobbooster-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobbooster-backend
    depends_on:
      - qdrant
      - langfuse
    ports:
      - "8000:8000"
    environment:
      # API
      - DEBUG=false

      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}

      # Google Gemini
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-pro}

      # Qdrant
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=user_info
      - QDRANT_CLUSTER=jobbooster

      # Langfuse
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_HOST=http://langfuse:3000

      # Models
      - EMBEDDING_MODEL=intfloat/multilingual-e5-base
      - RERANKER_MODEL=bclavie/bge-reranker-base
    volumes:
      - ./backend:/app
      - backend_cache:/root/.cache
    restart: unless-stopped
    networks:
      - jobbooster-network

volumes:
  qdrant_data:
  langfuse_db_data:
  backend_cache:

networks:
  jobbooster-network:
    driver: bridge
