analyze_offer:
  description: >
    Analyse l’offre d’emploi fournie en texte brut.
    Identifie les éléments clés (intitulé, type de poste, entreprise, stack technique, compétences exigées, qualités recherchées, ton de communication, valeurs implicites).

    Offre d'emploi :
    {job_offer}
  expected_output: >
    JSON contenant les sections suivantes :
      {
        "entreprise": "...",
        "poste": "...",
        "secteur": "...",
        "missions": ["..."],
        "compétences": ["..."],
        "technologies": ["..."],
        "soft_skills": ["..."],
        "valeurs": ["..."],
        "ton_recruteur": "...",
        "agent": {agent},
        "résumé_concis": "3 phrases maximum résumant l’offre"
      }
  agent: analyzer

write_email:
  description: >
    Rédige un email de motivation court à partir du contexte complet (offre, analyse, RAG).
  expected_output: >
    Email professionnel de 6 à 8 lignes maximum.
  agent: email_writer
  context:
    - job_offer
    - analysis
    - rag_context

write_linkedin:
  description: >
    Rédige un message LinkedIn concis et percutant à partir du contexte complet.
  expected_output: >
    Message LinkedIn professionnel de 3 à 5 phrases maximum.
  agent: linkedin_writer
  context:
    - job_offer
    - analysis
    - rag_context

write_letter:
  description: >
    Rédige une lettre de motivation complète en respectant le RULESET: LETTER.
  expected_output: >
    Lettre de motivation professionnelle en 4 paragraphes maximum, prête à envoyer.
  agent: letter_writer
  context:
    - job_offer
    - analysis
    - rag_context
