analyze_offer:
  description: >
    Analyse l’offre d’emploi fournie en texte brut.
    Identifie les éléments clés (intitulé, type de poste, entreprise, stack technique, compétences exigées, qualités recherchées, ton de communication, valeurs implicites).

    Offre d'emploi :
    {job_offer}
  expected_output: >
    JSON contenant les sections suivantes :
      {
        "entreprise": "...",
        "poste": "...",
        "secteur": "...",
        "missions": ["..."],
        "compétences": ["..."],
        "technologies": ["..."],
        "soft_skills": ["..."],
        "valeurs": ["..."],
        "ton_recruteur": "...",
        "résumé_concis": "3 phrases maximum résumant l’offre"
      }
  agent: analyzer

write_email:
  description: >
    À partir du résumé de l’offre et des informations du candidat (issues du RAG), rédige un email de motivation court conforme au RULESET: EMAIL.
  expected_output: >
    Email professionnel de 6 à 8 lignes maximum, prêt à être envoyé.
  agent: email_writer
  context:
    - analyze_offer
    - candidate_context

write_linkedin:
  description: >
    À partir du résumé de l’offre et des informations du candidat,
    rédige un message LinkedIn court, percutant et personnalisé.
  expected_output: >
    Message LinkedIn de 3 à 5 phrases maximum, prêt à être envoyé.
  agent: linkedin_writer
  context:
    - analyze_offer
    - candidate_contex

write_letter:
  description: >
    À partir du résumé de l’offre et des informations du candidat, rédige une lettre de motivation complète conforme au RULESET: LETTER.
  expected_output: >
    Lettre de motivation professionnelle en 4 paragraphes maximum, prête à envoyer.
  agent: letter_writer
  context:
    - analyze_offer
    - candidate_context
